### ISSUE TITLE
Deprecated hApp behavior is non-intuitive

### ISSUE THREAD

**Issue by zippy** [holochain/devhub-gui#14]
Currently when you deprecate a hApp, it disappears from your own hApp list.  This seem seems weird, you shoud probably still be able to update the description, or maybe even "undeprecate" a happ.  And it's more likely that it should be removed from the "All hApps" list perhaps with some options somewhere that allow you to include deprecated happs.

It seems like we should also be able to delete a hApp completely in the case where you created something totally by mistake.

**Comment by mjbrisebois** [comment]
These are excellent points.

1. The bug where deprecated items were showing up in lists was unintentional and is now fixed.  
2. There is a method in the DNAs for fetching "My deprecated things".  The plan is to make a page for viewing deprecated things.  I will add "un-deprecate" to the queue.
3. I will also add "delete" to the queue, especially if an item has no published releases or versions.
