### ISSUE TITLE
UI bug:  Clicking on left-arrow does nothing.

### ISSUE THREAD

**Issue by zippy** [holochain/devhub-gui#15]
When you navigate into a happ and a release, I keep clicking on the left Arrow and it doesn't do anything even though the mouse turns to indicate click-ability.  I expect the arrow to take me up one level.

**Comment by mjbrisebois** [comment]
Perhaps the behavior of that button is too unintuitive.  It implements the `history.back()` call so it only works when there is a navigation history.  I should probably change it to navigating up the breadcrumbs.
