### ISSUE TITLE
impossible UX when creating new version when multiple DNAs exist

### ISSUE THREAD

**Issue by zippy** [holochain/devhub-gui#17]
If you have created multiple DNAs and are trying to add a new Release Version there are a number of problems:

1. the drop-down shows the DNAs with no indication of version or hash, so it's impossible to know which to choose.
2. the drop-down shows DNA's even if all of the DNAs have been un-published.  I had to deprecate the DNA for the item to be dropped from the menu.

**Comment by shanedeeodonnell** [comment]
Appending to this issue as this following will probably go away when above is fixed. You can type a zome name and hit enter multiple times, then delete the ones you don't want. I needed to have a description to differentiate between the though. 

When adding a 2nd zome by this hacky method, the pages refreshes and resets all progress.

<img width="767" alt="Screen Shot 2022-06-02 at 10 26 11 AM" src="https://user-images.githubusercontent.com/16504076/171652613-ed56e5b2-d792-434a-99f2-cd7d396694fd.png">
<img width="736" alt="Screen Shot 2022-06-02 at 10 29 29 AM" src="https://user-images.githubusercontent.com/16504076/171652986-c5118797-cf8d-438e-9a65-4d1b75ea86aa.png">

**Comment by mjbrisebois** [comment]
There is a complete redesign of the hApp bundle uploading page that has been released - https://github.com/holochain/devhub-gui/tree/v0.7.1

The new interface is much more intuitive.  It provides integrity checks, error feedback, and association context.  Please check it out :)
