### ISSUE TITLE
Unable to publish DNA if it contains zome with undefined dependencies

### ISSUE THREAD

**Issue by mattyg** [holochain/devhub-gui#31]
When attempting to publish a DNA that includes a zome that has no dependencies (it's a coordinator zome only), nothing happens in the UX and I get the following error in console

```
[ main       ] ERROR: Vue App Error (5): 
    TypeError: Object.values requires that input parameter not be null or undefined — 
    Proxy {_: Object, __v_skip: true, $debug: function, mustGet: function, catchStatusCodes: function, …}
```

The error is throw from this line: https://github.com/holochain/devhub-gui/blob/6f7544ee0b2d090b50941983944a6bd40ab21ca0/src/dna_version_controllers.js#L837

I had specified the 0 dependency zome in my dna manifest like this:
```
    - name: ping
      hash: ~
      bundled: "../../../target/wasm32-unknown-unknown/release/ping.wasm"
      dependencies: ~
```

By specifying it like this I can publish as expected:
```
    - name: ping
      hash: ~
      bundled: "../../../target/wasm32-unknown-unknown/release/ping.wasm"
      dependencies: []
```

**Comment by mjbrisebois** [comment]
Thanks @mattyg

Your PR should do the trick.  I'll try to get it merged as soon as possible.
