### ISSUE TITLE
error while uploading a happ when happ 'locations' are specified as `url` not `bundled` (there are no raw bytes)

### ISSUE THREAD

**Issue by Connoropolous** [holochain/devhub-gui#7]
Because of files over 16mb being too big to be sent via websockets, some happs need to use the other `Location` variants... `path` or `url` instead of `bundled`. 

https://github.com/Connoropolous/holo-rea/releases/download/0.0.22-alpha/hrea_suite.happ
from https://github.com/Connoropolous/holo-rea/releases/tag/0.0.22-alpha

When trying to use the upload happ bundle feature, I see this in the console:

```
2022-02-28T15:46:55.699Z [ main       ] ERROR: Vue App Error (5): TypeError: can't convert undefined to object
    unzip gzip.js:189
    m happ_controllers.js:11
    w happ_controllers.js:605
    r happ_controllers.js:595
    l runtime.js:63
    _invoke runtime.js:294
    x runtime.js:119
```

**Comment by mjbrisebois** [comment]
I haven't forgotten about this.  Obviously, `path` cannot be supported in the GUI, so I plan to add a warning if that is found in the bundle.  `url` should be possible so I will add this to the queue.
